[package]
name = "impfuzzy"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ffuzzy = "0.3.6"
goblin = "0.5.1"
phf = { version = "0.11.2", features = ["macros"] }
